---
- name: Install httpd service
  hosts: appServers
  become: true
  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: latest
      update_cache: yes
  - name: copying index file to managed nodes
    copy:
      #name: copy index file to documentroot
      src: /var/lib/jenkins/workspace/Ansible-integration/index.html
      dest: /var/www/html/index.html
  - name: Start service
    service:
      name: httpd
      state: started
...
